
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module multicore(

	//////////// CLOCK //////////
	CLOCK_50,
	CLOCK2_50,
	CLOCK3_50,

	//////////// LED //////////
	LEDG,
	LEDR,

	//////////// KEY //////////
	KEY,
	//input 		          		UART_CTS,
	//output		          		UART_RTS,
			          		UART_RXD,
			          		UART_TXD,

	//////////// VGA //////////
			     		VGA_B,
		          		VGA_BLANK_N,
	          		VGA_CLK,
		VGA_G,
			          		VGA_HS,
		VGA_R,
			          		VGA_SYNC_N,
			          		VGA_VS	
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input		          		CLOCK_50;
input		          		CLOCK2_50;
input		          		CLOCK3_50;

//////////// LED //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY //////////
input		     [3:0]		KEY;
input 		          		UART_RXD;
	output		          		UART_TXD;

	//////////// VGA //////////
	output		     [7:0]		VGA_B;
	output		          		VGA_BLANK_N;
	output		          		VGA_CLK;
	output		     [7:0]		VGA_G;
	output		          		VGA_HS;
	output		     [7:0]		VGA_R;
	output		          		VGA_SYNC_N;
	output		          		VGA_VS;


//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [15:0] connect;

    Embedded u0 (
        .clk_clk                              (CLOCK_50),                              //                           clk.clk
        .reset_reset_n                        (KEY[0]),                        //                         reset.reset_n
        .reg16_0_conduit_end_readdata         (connect),         //           reg16_0_conduit_end.readdata
        .pioslave1_external_connection_export (connect), // pioslave1_external_connection.export
        .pioslave2_external_connection_export (connect),  // pioslave2_external_connection.export
		  .ledgslave1_external_connection_export (LEDG[7:0]), // ledgslave1_external_connection.export
        .ledrslave2_external_connection_export (LEDR[7:0]),  // ledrslave2_external_connection.export
		  .video_vga_controller_0_external_interface_CLK   (VGA_CLK),   // video_vga_controller_0_external_interface.CLK
        .video_vga_controller_0_external_interface_HS    (VGA_HS),    //                                          .HS
        .video_vga_controller_0_external_interface_VS    (VGA_VS),    //                                          .VS
        .video_vga_controller_0_external_interface_BLANK (VGA_BLANK_N), //                                          .BLANK
        .video_vga_controller_0_external_interface_SYNC  (VGA_SYNC_N),  //                                          .SYNC
        .video_vga_controller_0_external_interface_R     (VGA_R),     //                                          .R
        .video_vga_controller_0_external_interface_G     (VGA_G),     //                                          .G
        .video_vga_controller_0_external_interface_B     (VGA_B),     //                                          .B
        .uart_0_external_connection_rxd                  (UART_RXD),                  //                uart_0_external_connection.rxd
        .uart_0_external_connection_txd                  (UART_TXD)                   //                                          .txd
    );









//=======================================================
//  Structural coding
//=======================================================



endmodule
